import {ArrowUpRight,MapPin,Clock} from 'lucide-react';
import {restaurant,Locale,route,money} from '@/lib/restaurant';
import {copy as c} from '@/lib/copy';
import {Shell} from './shell';
import {Photo} from './photo';
import {Contact} from './contact';
import {HeroFilm} from './hero-film';
export function Home({locale:l}:{locale:Locale}){const featured=restaurant.menu[1].items[0];const pt=l==='pt';return <Shell locale={l}><a className="reservation-rail" href={route(l,'reservas')}><span>{c.book[l]}</span></a><main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">{c.heroKicker[l]}</p><h1>{c.heroA[l]}<br/>{c.heroB[l]}<br/><em>{c.heroC[l]}</em></h1><p>{c.heroText[l]}</p><div className="actions"><a className="button" href={route(l,'reservas')}>{c.book[l]}<ArrowUpRight size={17}/></a><a className="text-link" href={route(l,'menu')}>{c.explore[l]}<ArrowUpRight size={16}/></a></div></div><div className="hero-visual"><HeroFilm alt={c.heroAlt[l]}/><span>{c.heroCaption[l]}</span></div></section><div className="essentials"><a href="#visitar"><MapPin size={16}/>{restaurant.location[l]}</a><a href="#visitar"><Clock size={16}/>{c.hoursShort[l]}</a><a href={route(l,'menu')}>{c.priceRange[l]}<ArrowUpRight size={15}/></a></div>
<section className="house-principles" aria-label={pt?'O que nos guia':'What guides us'}><div className="principles-image"><Photo kind="brasa" alt={pt?'Cozinha à brasa em movimento. Imagem criada para a demo.':'Cooking over embers in motion. Image created for the demo.'}/><span>{pt?'A cozinha começa no fogo.':'The kitchen starts with fire.'}</span></div><div className="principles-copy"><p className="eyebrow">{pt?'A MESA, À NOSSA MANEIRA':'THE TABLE, OUR WAY'}</p><p className="principles-statement">{pt?'Produto próximo, brasa atenta e conversa demorada.':'Local produce, attentive embers and lingering conversation.'}</p><div className="principles-list"><span>01 <b>{pt?'Estação':'Season'}</b></span><span>02 <b>{pt?'Partilha':'Sharing'}</b></span><span>03 <b>{pt?'Hospitalidade':'Hospitality'}</b></span></div></div></section>
<section className="section menu-teaser" id="mesa"><div className="section-intro"><div><p className="eyebrow">{c.season[l]}</p><h2>{c.menuTitle[l]}<br/><em>{c.menuTitleEm[l]}</em></h2></div><p className="section-description">{c.menuIntro[l]}</p></div><div className="featured-grid"><a className="feature-photo" href={route(l,'menu')}><Photo kind="dish" alt={c.dishAlt[l]}/><span className="photo-label">{c.signature[l]}<ArrowUpRight size={20}/></span></a><div className="featured-menu"><p className="eyebrow">{pt?'DA HORTA AO MAR':'FROM GARDEN TO SEA'}</p>{[restaurant.menu[0].items[1],featured,restaurant.menu[2].items[0]].map(item=><article key={item.id}><div><h3>{item.name[l]}</h3><span>{money(item.price,l)}</span></div><p>{item.description[l]}</p></article>)}<a className="text-link" href={route(l,'menu')}>{pt?'Conhecer o menu completo':'Discover the full menu'}<ArrowUpRight size={17}/></a></div></div></section>
<section className="story" id="casa"><div className="story-image"><Photo kind="table" alt={c.tableAlt[l]}/></div><div className="story-copy"><p className="eyebrow">{c.storyLabel[l]}</p><h2>{c.storyTitle[l]}<br/><em>{c.storyEm[l]}</em></h2><p>{c.storyText[l]}</p><p>{c.storySecond[l]}</p><a className="text-link" href={route(l,'reservas')}>{c.storyLink[l]}<ArrowUpRight size={17}/></a><span className="story-signature">Casa do Pátio</span></div></section>
<section className="gallery" id="ambiente" aria-labelledby="gallery-title"><div className="gallery-intro"><p className="eyebrow">{c.galleryLabel[l]}</p><h2 id="gallery-title">{c.galleryTitle[l]}</h2></div><div className="gallery-grid"><figure className="gallery-courtyard"><Photo kind="hero" alt={c.heroAlt[l]}/><figcaption>{c.galleryCaptions[0][l]}</figcaption></figure><figure className="gallery-dish"><Photo kind="dish" alt={c.dishAlt[l]}/><figcaption>{c.galleryCaptions[1][l]}</figcaption></figure><figure className="gallery-table"><Photo kind="table" alt={c.tableAlt[l]}/><figcaption>{c.galleryCaptions[2][l]}</figcaption></figure><figure className="gallery-service"><Photo kind="service" alt={pt?'Mesa preparada para o jantar. Imagem criada para a demo.':'A table prepared for dinner. Image created for the demo.'}/><figcaption>{pt?'04 / SERVIÇO SEM PRESSA':'04 / UNHURRIED SERVICE'}</figcaption></figure><figure className="gallery-brasa"><Photo kind="brasa" alt={pt?'Chef a trabalhar na brasa. Imagem criada para a demo.':'A chef working over embers. Image created for the demo.'}/><figcaption>{pt?'05 / BRASA ACESA':'05 / EMBERS ALIGHT'}</figcaption></figure><figure className="gallery-evening"><Photo kind="patioEvening" alt={pt?'Pátio de Lisboa ao anoitecer. Imagem criada para a demo.':'A Lisbon courtyard at twilight. Image created for the demo.'}/><figcaption>{pt?'06 / ANTES DA NOITE':'06 / BEFORE NIGHTFALL'}</figcaption></figure></div></section>
<section className="location-section" id="visitar" aria-labelledby="location-title"><div className="location-heading"><p className="eyebrow">{pt?'LOCALIZAÇÃO PROVISÓRIA':'TEMPORARY LOCATION'}</p><h2 id="location-title">{pt?'Visitar & horários':'Visit & opening hours'}</h2></div><div className="location-layout"><div className="location-details"><section><MapPin size={20}/><h3>{restaurant.location[l]}</h3><p>{pt?'Portugal · Bairro do Príncipe Real':'Portugal · Príncipe Real neighbourhood'}</p><p className="small-note">{pt?'Localização provisória e ilustrativa. Esta demo não corresponde a um restaurante ou morada comercial real.':'Temporary illustrative location. This demo does not represent a real restaurant or business address.'}</p><a className="text-link" href={restaurant.mapUrl} target="_blank" rel="noopener noreferrer">{c.mapArea[l]}<ArrowUpRight size={17}/></a></section><section><Clock size={20}/><h3>{c.hours[l]}</h3><p>{c.days[l]}</p><dl><div><dt>{c.lunch[l]}</dt><dd>{restaurant.hours.lunch.join(' — ')}</dd></div><div><dt>{c.dinner[l]}</dt><dd>{restaurant.hours.dinner.join(' — ')}</dd></div></dl><p className="small-note">{c.closed[l]}</p></section></div><div className="location-map"><iframe title={pt?'Mapa provisório da localização':'Temporary location map'} src="https://www.google.com/maps?q=Jardim%20do%20Pr%C3%ADncipe%20Real%2C%20Lisboa&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>
<section className="section faq"><div><p className="eyebrow">{c.faqLabel[l]}</p><h2>{c.faqTitle[l]}</h2></div><div>{c.faq.slice(0,3).map((faq,i)=><details key={i}><summary>{faq.q[l]}<span aria-hidden="true">+</span></summary><p>{faq.a[l]}</p></details>)}</div></section><Contact locale={l}/>
 </main></Shell>}
