import {ArrowUpRight,MapPin,Clock,MoveDown} from 'lucide-react';
import {restaurant,Locale,route,money} from '@/lib/restaurant';
import {copy as c} from '@/lib/copy';
import {Shell} from './shell';
import {Photo} from './photo';
import {Contact} from './contact';
export function Home({locale:l}:{locale:Locale}){const featured=restaurant.menu[1].items[0];const pt=l==='pt';return <Shell locale={l}><main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">{c.heroKicker[l]}<span className="tiny-line"/></p><h1>{c.heroA[l]}<br/>{c.heroB[l]}<br/><em>{c.heroC[l]}</em></h1><p>{c.heroText[l]}</p><div className="actions"><a className="button" href={route(l,'reservas')}>{c.book[l]}<ArrowUpRight size={17}/></a><a className="text-link" href={route(l,'menu')}>{c.explore[l]}</a></div><p className="hero-demo">{c.demo[l]}</p></div><div className="hero-visual"><Photo kind="hero" alt={c.heroAlt[l]} priority/><span>{c.heroCaption[l]}</span></div><a href="#mesa" className="scroll-cue" aria-label={pt?'Descobrir a casa':'Discover the house'}><MoveDown size={16}/></a></section><div className="essentials"><a href="#visitar"><MapPin size={16}/>{restaurant.location[l]}</a><a href="#visitar"><Clock size={16}/>{c.hoursShort[l]}</a><a href={route(l,'menu')}>{c.priceRange[l]}<ArrowUpRight size={15}/></a></div>
<section className="section menu-teaser" id="mesa"><div className="section-intro"><div><p className="eyebrow">{c.season[l]}</p><h2>{c.menuTitle[l]}<br/><em>{c.menuTitleEm[l]}</em></h2></div><p className="section-description">{c.menuIntro[l]}</p></div><div className="featured-grid"><a className="feature-photo" href={route(l,'menu')}><Photo kind="dish" alt={c.dishAlt[l]}/><span className="photo-label">{c.signature[l]}<ArrowUpRight size={20}/></span></a><div className="featured-menu"><p className="eyebrow">{pt?'DA HORTA AO MAR':'FROM GARDEN TO SEA'}</p>{[restaurant.menu[0].items[1],featured,restaurant.menu[2].items[0]].map(item=><article key={item.id}><div><h3>{item.name[l]}</h3><span>{money(item.price,l)}</span></div><p>{item.description[l]}</p></article>)}<a className="text-link" href={route(l,'menu')}>{pt?'Conhecer o menu completo':'Discover the full menu'}<ArrowUpRight size={17}/></a></div></div></section>
<section className="story" id="casa"><div className="story-image"><Photo kind="table" alt={c.tableAlt[l]}/></div><div className="story-copy"><p className="eyebrow">{c.storyLabel[l]}</p><h2>{c.storyTitle[l]}<br/><em>{c.storyEm[l]}</em></h2><p>{c.storyText[l]}</p><p>{c.storySecond[l]}</p><a className="text-link" href={route(l,'reservas')}>{c.storyLink[l]}<ArrowUpRight size={17}/></a><span className="story-signature">Casa do Pátio</span></div></section>
{restaurant.features.gallery&&<section className="section gallery" id="galeria"><div className="section-intro"><div><p className="eyebrow">{c.galleryLabel[l]}</p><h2>{c.galleryTitle[l]}</h2></div><span className="gallery-count">01 — 03</span></div><div className="gallery-grid">{(['hero','dish','table'] as const).map((kind,i)=><figure key={kind}><Photo kind={kind} alt={[c.heroAlt[l],c.dishAlt[l],c.tableAlt[l]][i]}/><figcaption>{c.galleryCaptions[i][l]}</figcaption></figure>)}</div></section>}
{restaurant.features.promotions&&<section className="occasion section"><div><p className="eyebrow">{pt?'HÁ DIAS QUE PEDEM MAIS TEMPO':'SOME DAYS ASK YOU TO STAY'}</p><h2>{pt?'Um almoço sem pressa.':'A leisurely lunch.'}</h2><p>{pt?'De terça a sexta, uma entrada, um prato e um café. O nosso convite para fazer uma pausa a meio do dia.':'Tuesday to Friday, a starter, a main and an espresso. Our invitation to take a break in the middle of your day.'}</p><span className="small-note">{pt?'Proposta ilustrativa · 12:30–15:00 · Bebidas à parte':'Illustrative offer · 12:30–15:00 · Drinks not included'}</span></div><div className="occasion-price"><span>24 €</span><p>{pt?'por pessoa':'per person'}</p><a className="text-link" href={route(l,'reservas')}>{c.book[l]}<ArrowUpRight size={16}/></a></div></section>}
{restaurant.features.events&&<section className="event-strip"><p className="eyebrow">{pt?'À VOLTA DA MESA':'AROUND THE TABLE'}</p><div><h3>{pt?'Uma noite, os sabores da estação.':'One evening, the flavours of the season.'}</h3><p>{pt?'Jantar de partilha · 5 momentos · 48 € por pessoa · Data a anunciar':'Sharing dinner · 5 courses · €48 per person · Date to be announced'}</p><small>{pt?'Evento ilustrativo, sem inscrições abertas.':'Illustrative event, no bookings open.'}</small></div><a className="text-link" href={route(l,'menu')}>{c.menu[l]}<ArrowUpRight size={16}/></a></section>}
{restaurant.features.reviews&&<section className="quote-section"><p className="eyebrow">{pt?'À SAÍDA, FICA A VONTADE DE VOLTAR':'LEAVE WITH A REASON TO RETURN'}</p><blockquote>“{pt?'Daquelas mesas onde o jantar acaba, mas a conversa fica.':'One of those tables where dinner ends, but the conversation stays.'}”</blockquote><p>{pt?'Testemunho ilustrativo · Não é uma avaliação de um cliente real':'Illustrative testimonial · Not a review from a real customer'}</p></section>}
<section className="section visit" id="visitar"><div className="visit-copy"><p className="eyebrow">{c.visitLabel[l]}</p><h2>{c.visitTitle[l]}<br/><em>{c.visitEm[l]}</em></h2><p>{c.neighborhood[l]}</p><a className="text-link" href={restaurant.mapUrl} target="_blank" rel="noopener noreferrer">{c.mapArea[l]}<ArrowUpRight size={17}/></a><p className="small-note">{c.addressNote[l]}</p></div><div className="visit-details"><div><MapPin size={21}/><h3>{restaurant.location[l]}</h3><p>{pt?'Portugal · Bairro do Príncipe Real':'Portugal · Príncipe Real neighbourhood'}</p></div><div><Clock size={21}/><h3>{c.hours[l]}</h3><p>{c.days[l]}</p><dl><div><dt>{c.lunch[l]}</dt><dd>{restaurant.hours.lunch.join(' — ')}</dd></div><div><dt>{c.dinner[l]}</dt><dd>{restaurant.hours.dinner.join(' — ')}</dd></div></dl><p className="small-note">{c.closed[l]}</p></div><Contact locale={l}/></div></section>
<section className="section faq"><div><p className="eyebrow">{c.faqLabel[l]}</p><h2>{c.faqTitle[l]}</h2></div><div>{c.faq.map((faq,i)=><details key={i}><summary>{faq.q[l]}<span aria-hidden="true">+</span></summary><p>{faq.a[l]}</p></details>)}</div></section>
<section className="final-cta"><p className="eyebrow">{pt?'PONHA A CONVERSA EM DIA':'LET’S CATCH UP'}</p><h2>{c.lastTitle[l]}<br/><em>{c.lastEm[l]}</em></h2><p>{c.lastText[l]}</p><a className="button" href={route(l,'reservas')}>{c.book[l]}<ArrowUpRight size={17}/></a></section></main></Shell>}
