import {ArrowUpRight,Car,Clock,MapPin,Navigation,Phone,TrainFront} from 'lucide-react';
import {restaurant,Locale,route} from '@/lib/restaurant';
import {copy as c} from '@/lib/copy';
import {Shell} from './shell';
import {Photo} from './photo';
import {Contact} from './contact';
import {HeroFilm} from './hero-film';
import {SignatureDishes} from './signature-dishes';
import {Reviews} from './reviews';
import {ReservationCta} from './reservation-cta';

export function Home({locale}:{locale:Locale}) {
  const pt=locale==='pt';
  return <Shell locale={locale}>
    <a className="reservation-rail" href={route(locale,'reservas')}><span>{c.book[locale]}</span></a>
    <main id="main">
      <section className="hero">
        <div className="hero-copy"><p className="eyebrow">{c.heroKicker[locale]}</p><h1>{c.heroA[locale]}<br/>{c.heroB[locale]}<br/><em>{c.heroC[locale]}</em></h1><p>{pt?'Cozinha portuguesa contemporânea no Príncipe Real.':'Contemporary Portuguese cooking in Príncipe Real.'}</p><div className="actions"><a className="button" href={route(locale,'reservas')}>{c.book[locale]}<ArrowUpRight size={17}/></a><a className="text-link" href={route(locale,'menu')}>{c.explore[locale]}<ArrowUpRight size={16}/></a></div></div>
        <div className="hero-visual"><HeroFilm alt={c.heroAlt[locale]}/><span>{c.heroCaption[locale]}</span></div>
      </section>
      <div className="essentials"><a href="#visitar"><MapPin size={16}/>{restaurant.location[locale]}</a><a href="#visitar"><Clock size={16}/>{c.hoursShort[locale]}</a><a href={route(locale,'menu')}>{restaurant.priceRange[locale]}<ArrowUpRight size={15}/></a></div>
      <SignatureDishes locale={locale}/>
      <section className="house-principles" aria-label={pt?'O que nos guia':'What guides us'}><div className="principles-image"><Photo kind="brasa" alt={pt?'Cozinha à brasa em movimento. Imagem criada para a demo.':'Cooking over embers in motion. Image created for the demo.'}/><span>{pt?'A cozinha começa no fogo.':'The kitchen starts with fire.'}</span></div><div className="principles-copy"><p className="eyebrow">{pt?'A MESA, À NOSSA MANEIRA':'THE TABLE, OUR WAY'}</p><p className="principles-statement">{pt?'Produto próximo, brasa atenta e conversa demorada.':'Local produce, attentive embers and lingering conversation.'}</p><div className="principles-list"><span>01 <b>{pt?'Estação':'Season'}</b></span><span>02 <b>{pt?'Partilha':'Sharing'}</b></span><span>03 <b>{pt?'Hospitalidade':'Hospitality'}</b></span></div></div></section>
      <section className="story" id="casa"><div className="story-image"><Photo kind="table" alt={c.tableAlt[locale]}/></div><div className="story-copy"><p className="eyebrow">{c.storyLabel[locale]}</p><h2>{c.storyTitle[locale]}<br/><em>{c.storyEm[locale]}</em></h2><p>{c.storyText[locale]}</p><p>{c.storySecond[locale]}</p><a className="text-link" href={route(locale,'reservas')}>{c.storyLink[locale]}<ArrowUpRight size={17}/></a><span className="story-signature">Casa do Pátio</span></div></section>
      {restaurant.features.gallery&&<section className="gallery" id="ambiente" aria-labelledby="gallery-title"><div className="gallery-intro"><p className="eyebrow">{c.galleryLabel[locale]}</p><h2 id="gallery-title">{c.galleryTitle[locale]}</h2></div><div className="gallery-grid"><figure className="gallery-courtyard"><Photo kind="hero" alt={c.heroAlt[locale]}/><figcaption>{c.galleryCaptions[0][locale]}</figcaption></figure><figure className="gallery-dish"><Photo kind="dish" alt={c.dishAlt[locale]}/><figcaption>{c.galleryCaptions[1][locale]}</figcaption></figure><figure className="gallery-table"><Photo kind="table" alt={c.tableAlt[locale]}/><figcaption>{c.galleryCaptions[2][locale]}</figcaption></figure><figure className="gallery-service"><Photo kind="service" alt={pt?'Mesa preparada para o jantar. Imagem criada para a demo.':'A table prepared for dinner. Image created for the demo.'}/><figcaption>{pt?'04 / SERVIÇO SEM PRESSA':'04 / UNHURRIED SERVICE'}</figcaption></figure><figure className="gallery-brasa"><Photo kind="brasa" alt={pt?'Chef a trabalhar na brasa. Imagem criada para a demo.':'A chef working over embers. Image created for the demo.'}/><figcaption>{pt?'05 / BRASA ACESA':'05 / EMBERS ALIGHT'}</figcaption></figure><figure className="gallery-evening"><Photo kind="patioEvening" alt={pt?'Pátio de Lisboa ao anoitecer. Imagem criada para a demo.':'A Lisbon courtyard at twilight. Image created for the demo.'}/><figcaption>{pt?'06 / ANTES DA NOITE':'06 / BEFORE NIGHTFALL'}</figcaption></figure></div></section>}
      <Reviews locale={locale}/>
      <section className="location-section" id="visitar" aria-labelledby="location-title"><div className="location-heading"><p className="eyebrow">{pt?'VISITAR':'VISIT'}</p><h2 id="location-title">{pt?'Visitar & horários':'Visit & opening hours'}</h2></div><div className="location-layout"><div className="location-details"><section><MapPin size={20}/><h3>{restaurant.location[locale]}</h3><p>{restaurant.address[locale]}</p><p className="small-note">{c.addressNote[locale]}</p><div className="location-actions"><a className="button" href={restaurant.mapUrl} target="_blank" rel="noopener noreferrer">{pt?'Como chegar':'Get directions'}<Navigation size={16}/></a><a className="text-link" href={restaurant.appleMapsUrl} target="_blank" rel="noopener noreferrer">Apple Maps<ArrowUpRight size={16}/></a></div></section><section><Clock size={20}/><h3>{c.hours[locale]}</h3><p>{c.days[locale]}</p><dl><div><dt>{c.lunch[locale]}</dt><dd>{restaurant.hours.lunch.join(' — ')}</dd></div><div><dt>{c.dinner[locale]}</dt><dd>{restaurant.hours.dinner.join(' — ')}</dd></div></dl><p className="small-note">{c.closed[locale]}</p></section><section className="visit-extras"><div><TrainFront size={18}/><span>{restaurant.visit.transport[locale]}</span></div><div><Car size={18}/><span>{restaurant.visit.parking[locale]}</span></div>{restaurant.phone&&<a href={`tel:${restaurant.phone}`}><Phone size={18}/>{restaurant.phone}</a>}</section></div><div className="location-map"><iframe title={pt?'Mapa provisório da localização':'Temporary location map'} src="https://www.google.com/maps?q=Jardim%20do%20Pr%C3%ADncipe%20Real%2C%20Lisboa&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>
      <section className="section faq"><div><p className="eyebrow">{c.faqLabel[locale]}</p><h2>{c.faqTitle[locale]}</h2></div><div>{c.faq.slice(0,3).map((faq,i)=><details key={i}><summary>{faq.q[locale]}<span aria-hidden="true">+</span></summary><p>{faq.a[locale]}</p></details>)}</div></section>
      <ReservationCta locale={locale}/><Contact locale={locale}/>
    </main>
  </Shell>;
}
