export type Locale = 'pt' | 'en';
export type Localized = Record<Locale,string>;
export const tr=(pt:string,en:string):Localized=>({pt,en});
export type MenuItem={id:string;name:Localized;description:Localized;price:number;allergens:Localized;diet?:'vegan'|'vegetarian';featured?:boolean;available:boolean};
export type MenuCategory={id:string;name:Localized;note:Localized;items:MenuItem[]};
export interface RestaurantConfig{id:string;name:string;demo:boolean;origin:string;location:Localized;phone:string|null;whatsapp:string|null;email:string|null;mapUrl:string;timezone:string;currency:string;theme:{cream:string;ink:string;accent:string};features:{reservations:boolean;ordering:boolean;gallery:boolean;reviews:boolean;events:boolean;promotions:boolean};hours:{closedDay:number;lunch:[string,string];dinner:[string,string]};images:{hero:string;dish:string;table:string};menu:MenuCategory[]}
export const restaurant:RestaurantConfig={id:'casa-do-patio-demo',name:'Casa do Pátio',demo:true,origin:'https://casa-do-patio-tiago-team2.vercel.app',location:tr('Príncipe Real, Lisboa','Príncipe Real, Lisbon'),phone:null,whatsapp:null,email:null,mapUrl:'https://www.google.com/maps/search/?api=1&query=Jardim+do+Pr%C3%ADncipe+Real+Lisboa',timezone:'Europe/Lisbon',currency:'EUR',theme:{cream:'#f4efe4',ink:'#201d18',accent:'#8f3f2a'},features:{reservations:true,ordering:false,gallery:false,reviews:false,events:false,promotions:false},hours:{closedDay:1,lunch:['12:30','15:00'],dinner:['19:00','23:00']},images:{hero:'/images/courtyard',dish:'/images/octopus',table:'/images/table'},menu:[
{id:'partilhar',name:tr('Para começar','To begin'),note:tr('Peça mais um prato. Há sempre espaço à mesa.','One more plate. There is always room at the table.'),items:[
{id:'pao',name:tr('Pão, azeite & companhia','Bread, olive oil & company'),description:tr('Massa-mãe, azeite do Alentejo e manteiga de alho assado.','Sourdough, Alentejo olive oil and roasted garlic butter.'),price:5.5,allergens:tr('Glúten, leite','Gluten, milk'),diet:'vegetarian',available:true},
{id:'tomate',name:tr('O tomate da estação','Seasonal tomatoes'),description:tr('Tomates de variedades antigas, pêssego, manjericão e vinagrete de vinho.','Heritage tomatoes, peach, basil and wine vinaigrette.'),price:10,allergens:tr('Sulfitos','Sulphites'),diet:'vegan',available:true},
{id:'croquetes',name:tr('Croquetes de cozido','Portuguese stew croquettes'),description:tr('Quatro pequenas memórias do cozido, com mostarda da casa.','Four little memories of Portuguese stew, with house mustard.'),price:9,allergens:tr('Glúten, ovo, leite, mostarda','Gluten, egg, milk, mustard'),available:true},
{id:'ameijoas',name:tr('Amêijoas à nossa maneira','Clams, our way'),description:tr('Alho, coentros, vinho branco e pão para não deixar nada.','Garlic, coriander, white wine and bread for the very last drop.'),price:17,allergens:tr('Moluscos, glúten, sulfitos','Molluscs, gluten, sulphites'),available:true}]},
{id:'principais',name:tr('Da nossa cozinha','From our kitchen'),note:tr('O que a terra e o mar nos trazem de melhor.','The best of what our land and sea bring us.'),items:[
{id:'polvo',name:tr('Polvo, brasa & batata','Octopus, embers & potatoes'),description:tr('Polvo na brasa, batata a murro, grelos e azeite de alho.','Chargrilled octopus, crushed potatoes, turnip greens and garlic olive oil.'),price:26,allergens:tr('Moluscos','Molluscs'),featured:true,available:true},
{id:'arroz',name:tr('Arroz do mar','Rice from the sea'),description:tr('Arroz malandrinho de peixe e camarão, acabado com coentros.','Brothy rice with fish and prawns, finished with coriander.'),price:25,allergens:tr('Peixe, crustáceos, sulfitos','Fish, crustaceans, sulphites'),available:true},
{id:'porco',name:tr('Porco alentejano','Alentejo pork'),description:tr('Presa de porco, migas de pão e laranja fresca.','Pork shoulder steak, traditional bread migas and fresh orange.'),price:24,allergens:tr('Glúten','Gluten'),available:true},
{id:'horta',name:tr('Uma volta pela horta','A walk through the garden'),description:tr('Legumes assados, creme de feijão branco, amêndoa e ervas.','Roasted vegetables, white bean purée, almonds and herbs.'),price:19,allergens:tr('Frutos de casca rija','Tree nuts'),diet:'vegan',available:true}]},
{id:'doces',name:tr('Ficar mais um pouco','Stay a little longer'),note:tr('Há conversas que pedem sobremesa.','Some conversations call for dessert.'),items:[
{id:'leite',name:tr('Leite-creme queimado','Burnt custard'),description:tr('Baunilha, limão e uma crosta que estala à colher.','Vanilla, lemon and a delicate caramelised crust.'),price:7,allergens:tr('Leite, ovo','Milk, egg'),diet:'vegetarian',available:true},
{id:'chocolate',name:tr('Chocolate & azeite','Chocolate & olive oil'),description:tr('Mousse de chocolate negro, flor de sal e azeite virgem extra.','Dark chocolate mousse, sea salt and extra virgin olive oil.'),price:8,allergens:tr('Ovo, leite','Egg, milk'),diet:'vegetarian',available:true},
{id:'fruta',name:tr('Fruta no seu tempo','Fruit in its own time'),description:tr('Fruta da estação, sorbet de limão e hortelã.','Seasonal fruit, lemon sorbet and mint.'),price:7,allergens:tr('Sem alergénios declarados na receita; consulte a equipa.','No declared recipe allergens; please consult the team.'),diet:'vegan',available:true}]},
{id:'bebidas',name:tr('Para brindar','To raise a glass'),note:tr('De perto, de longe. Sempre em boa companhia.','From near and far. Always in good company.'),items:[
{id:'vinho',name:tr('Vinho da casa · copo','House wine · glass'),description:tr('Branco ou tinto português, escolhido para acompanhar a mesa.','Portuguese white or red, selected for the table.'),price:6,allergens:tr('Sulfitos','Sulphites'),available:true},
{id:'tonico',name:tr('Porto tónico','White port & tonic'),description:tr('Porto branco, tónica, laranja e alecrim.','White port, tonic, orange and rosemary.'),price:9,allergens:tr('Sulfitos','Sulphites'),available:true},
{id:'limonada',name:tr('Limonada do pátio','Courtyard lemonade'),description:tr('Limão, hortelã e um toque de gengibre.','Lemon, mint and a touch of ginger.'),price:4.5,allergens:tr('Sem alergénios declarados na receita; consulte a equipa.','No declared recipe allergens; please consult the team.'),diet:'vegan',available:true},
{id:'agua',name:tr('Água filtrada · 75 cl','Filtered water · 75 cl'),description:tr('Natural ou com gás.','Still or sparkling.'),price:2.5,allergens:tr('Nenhum','None'),available:true},
{id:'cafe',name:tr('Café','Espresso'),description:tr('O fim certo para uma boa refeição.','The right ending to a good meal.'),price:2,allergens:tr('Nenhum','None'),available:true}]}]};
export const money=(value:number,locale:Locale)=>new Intl.NumberFormat(locale==='pt'?'pt-PT':'en-IE',{style:'currency',currency:restaurant.currency,maximumFractionDigits:value%1===0?0:2}).format(value);
export const route=(locale:Locale,slug='')=>locale==='pt'&&!slug?'/':`/${locale}/${slug?slug+'/':''}`;
export const slots=['12:30','13:00','13:30','14:00','19:00','19:30','20:00','20:30','21:00','21:30'];
